defaults:
  - test_suites: lb_test
actors:
  hero:
    reward:
      entry_point: reward.valeo_action:ValeoAction
    terminal:
      entry_point: terminal.leaderboard:Leaderboard
carla_sh_path: /home/anthony/softwares/CARLA_0.9.11/CarlaUE4.sh
log_level: INFO
host: localhost
port: 2000
seed: 2021
no_rendering: true
kill_running: true
resume: true
wb_project: iccv21-roach-benchmark
wb_group: null
wb_tags: null
log_video: true
