defaults:
  - data_collect
  - _self_

dataset_root: /scratch3/datasets/roach/debug

n_episodes: 2

log_video: false
inject_noise: false
kill_running: true

actors:
  hero:
    terminal:
      kwargs:
        max_time: 500
